#!/usr/bin/env bash
# Emit a self-contained dice: data embedded, stateless POSIX-awk sampler.
set -euo pipefail

repo="$(cd "$(dirname -- "$0")" && pwd -P)"
out="${1:-$repo/dist/dice}"
case "$out" in /*) ;; *) out="$PWD/$out" ;; esac
cd "$repo"

delim="DICE_FORTUNE_EOF"
grep -q "^$delim\$" share/fortune && { echo "delimiter collision" >&2; exit 1; }

mkdir -p "$(dirname -- "$out")"
{
  cat <<'HEADER'
#!/usr/bin/env bash
# dice -- self-contained build (generated by build.sh; do not edit)
set -euo pipefail
sed '1,/^DICE_FORTUNE_EOF$/d' -- "$0" | awk -v seed="$RANDOM" '
  BEGIN { srand(seed) }
  /^%$/ { if (r != "" && rand() * ++n < 1) f = r; r = ""; next }
  { r = (r == "" ? $0 : r "\n" $0) }
  END { if (n) print f; else exit 1 }
'
exit $?
HEADER
  printf '%s\n' "$delim"
  cat share/fortune
} > "$out"
chmod +x "$out"
echo "$out ($(du -h "$out" | cut -f1))"
