#!/usr/bin/env bash
# Emit a self-contained dice: data embedded in one file.  Uses the
# system's fortune(6) when available; falls back to a POSIX-awk sampler.
set -euo pipefail
cd "$(dirname -- "$(readlink -f -- "$0")")"

out="${1:-dist/dice}"
delim="DICE_FORTUNE_EOF"

grep -q "^$delim\$" share/fortune && { echo "delimiter collision" >&2; exit 1; }

mkdir -p "$(dirname -- "$out")"
{
  cat <<'HEADER'
#!/usr/bin/env bash
# dice -- self-contained build (generated by build.sh; do not edit)
set -euo pipefail
d="${XDG_DATA_HOME:-$HOME/.local/share}/dice"
f="$d/fortune"
self="$(readlink -f -- "$0")"
mkdir -p "$d"
if [ ! -e "$f" ] || [ "$self" -nt "$f" ]; then
  sed -n '/^DICE_FORTUNE_EOF$/,$p' "$self" | sed '1d' > "$f"
  if command -v strfile >/dev/null; then
    strfile -s "$f" "$f.dat"
  else
    rm -f "$f.dat"
  fi
fi
if command -v fortune >/dev/null && [ -e "$f.dat" ]; then
  exec fortune "$f"
fi
exec awk -v seed="$RANDOM" '
  BEGIN { srand(seed) }
  /^%$/ { if (r != "" && rand() * ++n < 1) f = r; r = ""; next }
  { r = (r == "" ? $0 : r "\n" $0) }
  END { if (r != "" && rand() * ++n < 1) f = r; print f }
' "$f"
HEADER
  printf '%s\n' "$delim"
  cat share/fortune
} > "$out"
chmod +x "$out"
echo "$out ($(du -h "$out" | cut -f1))"
