#!/usr/bin/env bash
# Emit a self-contained dice: data embedded, selection by the system's
# fortune(6). Requires fortune-mod (fortune + strfile) on the target.
set -euo pipefail
cd "$(dirname -- "$(readlink -f -- "$0")")"

out="${1:-dist/dice}"
delim="DICE_FORTUNE_EOF"

grep -q "^$delim\$" share/fortune && { echo "delimiter collision" >&2; exit 1; }

mkdir -p "$(dirname -- "$out")"
{
  cat <<'HEADER'
#!/usr/bin/env bash
# dice -- self-contained build (generated by build.sh; do not edit)
set -euo pipefail
command -v fortune >/dev/null && command -v strfile >/dev/null ||
  { echo "dice: needs fortune-mod (fortune + strfile)" >&2; exit 1; }
d="${XDG_DATA_HOME:-$HOME/.local/share}/dice"
mkdir -p "$d"
self="$(readlink -f -- "$0")"
f="$d/fortune"
if [ ! -e "$f.dat" ] || [ "$self" -nt "$f" ]; then
  sed -n '/^DICE_FORTUNE_EOF$/,$p' "$self" | sed '1d' > "$f"
  strfile -s "$f" "$f.dat"
fi
exec fortune "$f"
HEADER
  printf '%s\n' "exit 0" "$delim"
  cat share/fortune
} > "$out"
chmod +x "$out"
echo "$out ($(du -h "$out" | cut -f1))"
